"""
SAMA Daily Digest — main entry point.
Runs story_draft every day. Runs community_digest on Mondays only.
Sends a combined HTML email via Resend.
"""
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts import story_draft, community_digest, send_email

GREEN = "#2D5016"
GOLD = "#C9A84C"


def build_html(story: str, digest: str | None) -> str:
    digest_section = ""
    if digest:
        digest_section = f"""
        <div style="margin-bottom:32px;">
          <h2 style="font-family:sans-serif;color:{GREEN};border-bottom:2px solid {GOLD};
                     padding-bottom:8px;margin-bottom:16px;">
            Community Digest
          </h2>
          <div style="font-family:sans-serif;font-size:14px;color:#2d3748;white-space:pre-wrap;line-height:1.7;">
            {digest}
          </div>
        </div>
        """

    story_section = f"""
        <div style="margin-bottom:32px;">
          <h2 style="font-family:sans-serif;color:{GREEN};border-bottom:2px solid {GOLD};
                     padding-bottom:8px;margin-bottom:16px;">
            Instagram Story Draft
          </h2>
          <div style="font-family:sans-serif;font-size:14px;color:#2d3748;white-space:pre-wrap;line-height:1.7;">
            {story}
          </div>
        </div>
    """

    return f"""
    <html><body style="background:#f7f5f0;padding:24px;">
      <div style="max-width:680px;margin:0 auto;background:#fff;border-radius:10px;
                  border-top:5px solid {GREEN};padding:32px;">
        <div style="text-align:center;margin-bottom:28px;">
          <h1 style="font-family:sans-serif;color:{GREEN};margin:0;font-size:24px;">
            SAMA Daily
          </h1>
          <p style="font-family:sans-serif;color:{GOLD};margin:4px 0 0;font-size:13px;
                    letter-spacing:0.05em;text-transform:uppercase;">
            Service &amp; Mercy Alliance · Grand Island, NY
          </p>
        </div>
        {digest_section}
        {story_section}
        <p style="font-family:sans-serif;font-size:11px;color:#a0aec0;margin-top:32px;
                  text-align:center;border-top:1px solid #e2e8f0;padding-top:16px;">
          Generated by SAMA AI · samagi.org · 1822 Huth Rd, Grand Island, NY
        </p>
      </div>
    </body></html>
    """


def main():
    now = datetime.now(timezone.utc)
    is_monday = now.weekday() == 0

    date_str = now.strftime("%B %-d, %Y")
    subject = f"SAMA Daily \u2014 {date_str}"

    print(f"[run_daily] {date_str} | Monday={is_monday}")

    story = story_draft.generate()
    digest = community_digest.generate() if is_monday else None

    html = build_html(story, digest)
    send_email.send(subject, html)
    print("[run_daily] Done.")


if __name__ == "__main__":
    main()
