"""
SAMA Community Digest — main entry point.
Runs community_digest on Mondays only. Sends HTML email via Resend.
"""
import os
import sys
from datetime import datetime, timezone
import markdown as md

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts import community_digest, send_email

GREEN = "#2D5016"
GOLD  = "#C9A84C"


def build_html(digest: str) -> str:
    return f"""
    <html><body style="background:#f7f5f0;padding:24px;">
      <div style="max-width:680px;margin:0 auto;background:#fff;border-radius:10px;
                  border-top:5px solid {GREEN};padding:32px;">
        <div style="text-align:center;margin-bottom:28px;">
          <h1 style="font-family:sans-serif;color:{GREEN};margin:0;font-size:24px;">
            SAMA Community Digest
          </h1>
          <p style="font-family:sans-serif;color:{GOLD};margin:4px 0 0;font-size:13px;
                    letter-spacing:0.05em;text-transform:uppercase;">
            Service &amp; Mercy Alliance · Grand Island, NY
          </p>
        </div>
        <div style="font-family:sans-serif;font-size:14px;color:#2d3748;line-height:1.8;">
          {digest}
        </div>
        <p style="font-family:sans-serif;font-size:11px;color:#a0aec0;margin-top:32px;
                  text-align:center;border-top:1px solid #e2e8f0;padding-top:16px;">
          Generated by SAMA AI · samagi.org · 1822 Huth Rd, Grand Island, NY
        </p>
      </div>
    </body></html>
    """


def main():
    now = datetime.now(timezone.utc)
    is_monday = now.weekday() == 0

    if not is_monday:
        print("[run_daily] Not Monday — nothing to send.")
        return

    date_str = now.strftime("%B %-d, %Y")
    subject = f"SAMA Community Digest — {date_str}"

    print(f"[run_daily] Monday {date_str} — running digest")

    digest_md = community_digest.generate()
    digest_html = md.markdown(digest_md, extensions=["extra"])

    html = build_html(digest_html)
    send_email.send(subject, html)
    print("[run_daily] Done.")


if __name__ == "__main__":
    main()
